import type { DatabaseSync } from "node:sqlite";
/** Remove tables absent from the pre-v20 migration fixtures, inside test databases only. */
export function removePostV19Tables(db: DatabaseSync) {
  for (const table of [
    "skill_heads",
    "skill_revisions",
    "skill_packages",
    "skill_import_receipts",
    "skill_selections",
    "skill_selection_receipts",
    "skill_quarantine",
    "skill_catalogs",
    "learning_policy",
    "learning_policy_receipts",
    "learning_work_consent",
    "learning_work_receipts",
    "learning_episodes",
    "learning_review_receipts",
    "learning_reflection_outputs",
    "environments",
    "environment_receipts",
    "environment_events",
    "browser_profiles",
    "browser_snapshots",
    "browser_control_receipts",
    "routines",
    "routine_receipts",
    "routine_occurrences",
    "tracked_works",
    "tracking_receipts",
    "tracking_polls",
    "tracking_followups",
    "attachments",
    "attachment_receipts",
    "source_dependencies",
    "skill_candidates",
    "candidate_revisions",
    "candidate_packages",
    "candidate_events",
    "candidate_receipts",
    "learning_evaluations",
    "evaluation_suites",
    "evaluation_suite_receipts",
    "evaluation_receipts",
    "evaluation_holdout_exposure",
    "learning_automation",
  ])
    db.exec(`DROP TABLE IF EXISTS ${table}`);
}
